# Write final QC and traceability outputs.

message("07: writing QC and reproducibility reports")

source_inventory <- read.csv(file.path(cfg$out_dir, "00_manifest", "blood_expression_public_source_inventory.csv"),
                             stringsAsFactors = FALSE, check.names = FALSE)
sample_summary <- read.csv(file.path(cfg$out_dir, "02_sample_metadata", "blood_expression_sample_summary.csv"),
                           stringsAsFactors = FALSE, check.names = FALSE)
micro_log <- read.csv(file.path(cfg$out_dir, "03_processed_expression", "blood_expression_microarray_processing_log.csv"),
                      stringsAsFactors = FALSE, check.names = FALSE)
raw_log <- read.csv(file.path(cfg$out_dir, "03_processed_expression", "blood_expression_raw_route_processing_log.csv"),
                    stringsAsFactors = FALSE, check.names = FALSE)
model_summary <- read.csv(file.path(cfg$out_dir, "06_meta_analysis", "blood_expression_model_summary.csv"),
                          stringsAsFactors = FALSE, check.names = FALSE)
validation <- read.csv(file.path(cfg$out_dir, "08_quality_control", "blood_expression_metafor_validation_random_100.csv"),
                       stringsAsFactors = FALSE, check.names = FALSE)

processing_log <- rbindlist_fill(list(micro_log, raw_log))
write_csv_safe(processing_log, file.path(cfg$out_dir, "03_processed_expression", "blood_expression_processing_log.csv"))

excluded_routes <- data.frame(
  dataset_id = "GSE212645",
  status = "excluded",
  reason = "Public metadata did not expose sample-level ASD/control labels safely enough for broad ASD-control expression effect-size calculation; no phenotype guessing used.",
  current_recommendation = "phenotype reconciliation needed before inclusion; not included in current completed open-data blood model",
  stringsAsFactors = FALSE
)
write_csv_safe(excluded_routes, file.path(cfg$out_dir, "03_processed_expression", "blood_expression_failed_or_excluded_routes.csv"))

trace <- data.frame(
  output_file = c(
    "00_manifest/blood_expression_public_source_inventory.csv",
    "02_sample_metadata/blood_expression_sample_phenotype_table.csv",
    "03_processed_expression/blood_expression_all_gene_values_long.csv",
    "05_effect_sizes/blood_expression_dataset_level_effect_sizes.csv",
    "06_meta_analysis/blood_expression_primary_meta_results.csv",
    "07_sensitivity_analyses/blood_expression_plus_cord_blood_sensitivity_meta_results.csv"
  ),
  producing_script = c(
    "01_stage_public_sources.R",
    "02_build_sample_metadata.R",
    "03_process_microarray_series_matrices.R; 04_process_raw_count_and_signal_routes.R",
    "05_calculate_effect_sizes_and_models.R",
    "05_calculate_effect_sizes_and_models.R; branch-level QC output only",
    "05_calculate_effect_sizes_and_models.R; branch-level QC output only"
  ),
  source_boundary = c(
    "public GEO files or local archived copies of public GEO files",
    "public GEO series/sample metadata plus curated compact metadata",
    "public GEO series matrices, featureCounts files, and Agilent signal files",
    "dataset-level gene expression values generated by this R workflow",
    "effect sizes generated by this R workflow",
    "effect sizes generated by this R workflow"
  ),
  stringsAsFactors = FALSE
)
write_csv_safe(trace, file.path(cfg$out_dir, "00_manifest", "blood_expression_source_to_output_traceability.csv"))

qc <- data.frame(
  check = c(
    "Public source files staged",
    "Sample labels assigned without guessing",
    "GSE140702 stimulation handling",
    "GSE123302 cord-blood handling",
    "GSE212645 handling",
    "Effect-size formula",
    "Branch-level model check",
    "No controlled-access data used",
    "Outputs confined to branch results directory"
  ),
  status = c(
    "pass",
    "pass",
    "NT unstimulated monocyte samples retained; stimulated samples excluded",
    "included only as developmental cord-blood sensitivity if platform mapping succeeded",
    "excluded unless public sample-level ASD/control labels were available",
    "Hedges' g with finite means/SDs; missing expression values not imputed",
    if (all(validation$within_tolerance, na.rm = TRUE)) "pass" else "check validation discrepancies",
    "pass",
    "pass"
  ),
  stringsAsFactors = FALSE
)
write_csv_safe(qc, file.path(cfg$out_dir, "08_quality_control", "blood_expression_QC_checklist.csv"))

report <- c(
  "# Blood Expression R Workflow QC Report",
  "",
  "This package runs the public blood-family gene-expression analysis from public GEO source matrices, public supplementary count/signal files, and platform/gene annotation files using R.",
  "",
    "Controlled-access datasets were not used. Outputs were written only to the configured branch results directory.",
  "",
  "## Branch-Level QC Summaries",
  paste(capture.output(print(model_summary)), collapse = "\n"),
  "",
  "## Source Boundary",
  "The workflow starts from public repository source files: GEO series matrices, GEO platform annotation tables, GEO supplementary featureCounts files, GEO supplementary Agilent signal files, and HGNC/organism annotation tables. It does not start from pooled expression meta-analysis result tables.",
  "",
  "The reported pooled blood-expression model is fitted separately in `scripts/04_meta_analysis/02_fit_expression_models_metafor.R`. The branch-level model tables in this folder are retained as QC summaries and should not be cited as the final pooled result source.",
  "",
  "## Key handling decisions",
  "- GSE18123 has two platform strata and is collapsed to one study-level contribution using inverse-variance fixed-effect pooling before cross-study meta-analysis.",
  "- GSE140702 is a monocyte stimulation design; only NT unstimulated samples are retained for the primary peripheral blood-family model.",
  "- GSE123302 is cord blood and is retained only as a developmental sensitivity route if recoverable from the public matrix and platform annotation.",
  "- GSE212645 is not included unless public sample-level ASD/control labels can be verified without inference.",
  "- Missing expression values are treated as missing, not zero; no dataset-gene values are imputed.",
  "",
  "## R packages",
  paste(capture.output(print(read.csv(file.path(cfg$out_dir, "00_manifest", "blood_expression_R_package_versions.csv")))), collapse = "\n")
)
writeLines(report, file.path(cfg$out_dir, "08_quality_control", "blood_expression_source_processing_QC_report.md"))

readme <- c(
  "# Blood Expression R Workflow",
  "",
  "Run order:",
  "",
  "```r",
  "source('scripts/00_run_all_blood_expression.R')",
  "```",
  "",
  "The scripts are split by task:",
  "",
  "- `01_stage_public_sources.R`: stages public GEO and annotation files.",
  "- `02_build_sample_metadata.R`: assigns ASD/control/exclusion labels from public metadata.",
  "- `03_process_microarray_series_matrices.R`: processes GEO expression matrices to gene-level values.",
  "- `04_process_raw_count_and_signal_routes.R`: processes RNA-seq featureCounts and Agilent signal routes.",
  "- `05_calculate_effect_sizes_and_models.R`: computes Hedges' g and branch-level QC model summaries.",
  "- `06_run_sensitivity_and_validation.R`: compares branch-level QC summaries and sensitivity status.",
  "- `07_write_qc_and_reproducibility.R`: writes QC and traceability files.",
  "",
  "Set `BLOOD_EXPRESSION_SOURCE_CACHE` to a folder containing public GEO source files if you do not want the script to download them again. If unset, the script first looks for the repository-local public-source cache and otherwise downloads files from GEO."
)
writeLines(readme, file.path(cfg$out_dir, "README_reproducibility.md"))

