#!/usr/bin/env Rscript

# Fit DNA methylation random-effects meta-analysis models.
#
# Input: dataset-level Hedges' g estimates generated by the methylation
# processing scripts in `pipelines/`.
# Output: gene-level DerSimonian-Laird random-effects estimates, FDR values,
# modified Knapp-Hartung interval classifications, and model summaries.

script_file <- normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]), winslash = "/", mustWork = TRUE)
script_dir <- dirname(script_file)
source(file.path(script_dir, "lib", "metafor_helpers.R"))

package_root <- normalizePath(file.path(script_dir, "..", ".."), winslash = "/", mustWork = TRUE)
output_dir <- file.path(package_root, "results", "meta_analysis", "methylation")

pipeline_path <- function(...) file.path(package_root, "pipelines", ...)

blood_meth_raw <- read_required(pipeline_path(
  "blood_methylation", "results",
  "array_blanks_as_missing_R_default", "blood_R_all_dataset_level_effect_sizes.csv"
))
brain_meth_raw <- read_required(pipeline_path(
  "brain_methylation", "results",
  "strict_missing_R_default", "brain_R_all_dataset_level_effect_sizes.csv"
))
placenta_meth_raw <- read_required(pipeline_path(
  "placenta_lcl_methylation", "results",
  "strict_missing_R_default", "placenta_R_all_dataset_level_effect_sizes.csv"
))
lcl_meth_raw <- read_required(pipeline_path(
  "placenta_lcl_methylation", "results",
  "strict_missing_R_default", "lcl_R_all_dataset_level_effect_sizes.csv"
))

blood_meth <- standardise_effects(
  blood_meth_raw, "blood_methylation", "dataset_id", "Hedges_g", "variance_g",
  "ASD_n", "control_n",
  extra_cols = c("meta_450k_primary_include", "meta_array_peripheral_include", "meta_all_available_with_cord_wgbs_include")
)
brain_meth <- standardise_effects(brain_meth_raw, "brain_methylation", "accession", "Hedges_g", "variance_g", "ASD_n", "control_n")
placenta_meth <- standardise_effects(placenta_meth_raw, "placenta_methylation", "accession", "Hedges_g", "variance_g", "ASD_n", "control_n")
lcl_meth <- standardise_effects(lcl_meth_raw, "lcl_methylation", "accession", "Hedges_g", "variance_g", "ASD_n", "control_n")

effects_by_input <- list(
  blood_methylation = blood_meth,
  brain_methylation = brain_meth,
  placenta_methylation = placenta_meth,
  lcl_methylation = lcl_meth
)

model_specs <- list()
add_model <- function(input_id, tissue_branch, model_name, model_role, datasets, notes = "", sensitivity_family = "") {
  model_specs[[length(model_specs) + 1L]] <<- list(
    input_id = input_id,
    omic_layer = "methylation",
    tissue_branch = tissue_branch,
    model_name = model_name,
    model_role = model_role,
    datasets = datasets,
    notes = notes,
    sensitivity_family = sensitivity_family
  )
}

add_model("blood_methylation", "blood", "blood_array_peripheral_primary", "primary",
          unique(blood_meth[parse_bool(meta_array_peripheral_include), dataset]),
          "Peripheral blood-family array model.", "primary")
add_model("blood_methylation", "blood", "blood_450k_only_sensitivity", "sensitivity",
          unique(blood_meth[parse_bool(meta_450k_primary_include), dataset]),
          "450K-only platform sensitivity.", "platform")
add_model("blood_methylation", "blood", "blood_array_plus_cord_WGBS_sensitivity", "sensitivity",
          unique(blood_meth[parse_bool(meta_all_available_with_cord_wgbs_include), dataset]),
          "Array plus cord-blood WGBS developmental sensitivity.", "WGBS/developmental")
add_model("blood_methylation", "blood", "blood_450k_plus_cord_WGBS_sensitivity", "sensitivity",
          c(unique(blood_meth[parse_bool(meta_450k_primary_include), dataset]), "GSE140730"),
          "450K plus cord-blood WGBS sensitivity.", "WGBS/developmental")

brain_defs <- read_required(pipeline_path(
  "brain_methylation", "results",
  "strict_missing_R_default", "brain_R_model_definitions.csv"
))
for (i in seq_len(nrow(brain_defs))) {
  add_model("brain_methylation", "post-mortem brain",
            brain_defs$model_name[i], brain_defs$role[i],
            split_dataset_string(brain_defs$datasets[i]),
            brain_defs$biological_interpretation[i],
            brain_defs$role[i])
}

add_model("placenta_methylation", "placenta", "placenta_primary_GSE178203_descriptive", "descriptive",
          "GSE178203", "Single-dataset placenta WGBS descriptive model.", "descriptive")
add_model("placenta_methylation", "placenta", "placenta_GSE67615_descriptive", "descriptive",
          "GSE67615", "Single-dataset placenta WGBS descriptive model.", "descriptive")
add_model("placenta_methylation", "placenta", "placenta_two_dataset_sensitivity", "sensitivity",
          c("GSE178203", "GSE67615"), "Two-dataset placenta WGBS sensitivity.", "two-dataset")
add_model("lcl_methylation", "LCL", "lcl_HM27_descriptive", "descriptive",
          "GSE34099", "HM27 LCL descriptive model.", "descriptive")
add_model("lcl_methylation", "LCL", "lcl_MeDIP_descriptive", "descriptive",
          "GSE99935", "MeDIP-chip LCL descriptive model.", "descriptive")
add_model("lcl_methylation", "LCL", "lcl_cross_assay_exploratory", "exploratory",
          c("GSE34099", "GSE99935"), "Cross-assay LCL exploratory synthesis.", "cross-assay")

write_model_outputs(model_specs, effects_by_input, output_dir, "methylation")
message("Methylation meta-analysis models completed.")

