#!/usr/bin/env Rscript

# Fit gene-expression random-effects meta-analysis models.
#
# Input: dataset-level Hedges' g estimates generated by the expression
# processing scripts in `pipelines/`.
# Output: gene-level DerSimonian-Laird random-effects estimates, FDR values,
# modified Knapp-Hartung interval classifications, and model summaries.

script_file <- normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]), winslash = "/", mustWork = TRUE)
script_dir <- dirname(script_file)
source(file.path(script_dir, "lib", "metafor_helpers.R"))

package_root <- normalizePath(file.path(script_dir, "..", ".."), winslash = "/", mustWork = TRUE)
output_dir <- file.path(package_root, "results", "meta_analysis", "expression")

pipeline_path <- function(...) file.path(package_root, "pipelines", ...)

blood_expr_raw <- read_required(pipeline_path(
  "blood_expression", "05_effect_sizes",
  "blood_expression_dataset_level_effect_sizes_raw_strata.csv"
))
blood_expr_collapsed <- collapse_within_study_platforms(blood_expr_raw)
blood_expr <- standardise_effects(
  blood_expr_collapsed, "blood_expression", "dataset", "hedges_g", "variance_g",
  "n_asd", "n_control", extra_cols = c("study_id", "model_role", "platform_id")
)

brain_expr <- standardise_effects(
  read_required(pipeline_path(
    "brain_expression", "05_effect_sizes",
    "brain_expression_R_dataset_level_effect_sizes_grouped_collapsed.csv"
  )),
  "brain_expression", "dataset", "hedges_g", "variance", "ASD_n", "control_n",
  extra_cols = c("assay", "region_group")
)

gse36315_dir <- pipeline_path("gse36315_brain_expression_sensitivity", "02_effect_size_inputs")
brain_expr_pfc <- standardise_effects(
  read_required(file.path(gse36315_dir, "collapsed_plus_GSE36315_pfc.csv")),
  "brain_expression_GSE36315_prefrontal_sensitivity", "dataset", "hedges_g", "variance", "ASD_n", "control_n",
  extra_cols = c("assay", "region_group")
)
brain_expr_cere <- standardise_effects(
  read_required(file.path(gse36315_dir, "collapsed_plus_GSE36315_cere.csv")),
  "brain_expression_GSE36315_cerebellum_sensitivity", "dataset", "hedges_g", "variance", "ASD_n", "control_n",
  extra_cols = c("assay", "region_group")
)
brain_expr_both <- standardise_effects(
  read_required(file.path(gse36315_dir, "collapsed_plus_GSE36315_both.csv")),
  "brain_expression_GSE36315_two_region_sensitivity", "dataset", "hedges_g", "variance", "ASD_n", "control_n",
  extra_cols = c("assay", "region_group")
)

lcl_expr <- standardise_effects(
  read_required(pipeline_path(
    "placenta_lcl_expression", "05_effect_sizes",
    "lcl_expression_R_dataset_level_effect_sizes.csv"
  )),
  "lcl_expression", "dataset", "hedges_g", "variance", "ASD_n", "control_n"
)

effects_by_input <- list(
  blood_expression = blood_expr,
  brain_expression = brain_expr,
  brain_expression_gse36315_pfc = brain_expr_pfc,
  brain_expression_gse36315_cere = brain_expr_cere,
  brain_expression_gse36315_both = brain_expr_both,
  lcl_expression = lcl_expr
)

model_specs <- list()
add_model <- function(input_id, tissue_branch, model_name, model_role, datasets, notes = "", sensitivity_family = "") {
  model_specs[[length(model_specs) + 1L]] <<- list(
    input_id = input_id,
    omic_layer = "expression",
    tissue_branch = tissue_branch,
    model_name = model_name,
    model_role = model_role,
    datasets = datasets,
    notes = notes,
    sensitivity_family = sensitivity_family
  )
}

blood_primary <- c("GSE111175", "GSE111176", "GSE140702", "GSE18123", "GSE25507", "GSE26415", "GSE77103")
add_model("blood_expression", "blood", "blood_expression_peripheral_primary", "primary",
          blood_primary, "Peripheral/postnatal blood-family expression model.", "primary")
add_model("blood_expression", "blood", "blood_expression_plus_cord_blood_sensitivity", "sensitivity",
          c(blood_primary, "GSE123302"), "Developmental sensitivity adding cord-blood expression.", "developmental")

brain_primary <- c("GSE113834", "GSE28475-GPL6883", "GSE28521", "GSE38322", "GSE102741", "GSE211154", "GSE236761", "GSE269105", "GSE59288", "GSE64018", "GSE62098")
add_model("brain_expression", "post-mortem brain", "brain_expression_grouped_primary_public_R", "primary",
          brain_primary, "Grouped post-mortem brain expression model.", "primary")
add_model("brain_expression", "post-mortem brain", "brain_expression_cortex_only_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE38322", "GSE102741", "GSE236761", "GSE59288", "GSE64018"), "Cortex-only region sensitivity.", "region")
add_model("brain_expression", "post-mortem brain", "brain_expression_cerebellum_only_sensitivity_R", "sensitivity",
          c("GSE38322", "GSE211154", "GSE269105"), "Cerebellum/Purkinje sensitivity.", "region")
add_model("brain_expression", "post-mortem brain", "brain_expression_prefrontal_cortex_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE102741", "GSE59288"), "Prefrontal cortex sensitivity.", "region")
add_model("brain_expression", "post-mortem brain", "brain_expression_BA19_occipital_sensitivity_R", "sensitivity",
          c("GSE38322", "GSE236761"), "BA19/occipital cortex sensitivity.", "region")
add_model("brain_expression", "post-mortem brain", "brain_expression_non_cortical_sensitivity_R", "sensitivity",
          "GSE62098", "Non-cortical corpus-callosum descriptive sensitivity.", "region")
add_model("brain_expression", "post-mortem brain", "brain_expression_microarray_only_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE28475-GPL6883", "GSE28521", "GSE38322"), "Microarray-only platform sensitivity.", "platform")
add_model("brain_expression", "post-mortem brain", "brain_expression_RNAseq_only_sensitivity_R", "sensitivity",
          c("GSE102741", "GSE211154", "GSE236761", "GSE269105", "GSE59288", "GSE64018", "GSE62098"), "RNA-seq-only platform sensitivity.", "platform")

add_model("brain_expression_gse36315_pfc", "post-mortem brain", "brain_expression_grouped_plus_GSE36315_prefrontal_custom_annotation_sensitivity_R", "sensitivity",
          c(brain_primary, "GSE36315_prefrontal_cortex_custom_annotation"), "Grouped-brain sensitivity adding custom-annotated GSE36315 prefrontal cortex.", "custom annotation")
add_model("brain_expression_gse36315_cere", "post-mortem brain", "brain_expression_grouped_plus_GSE36315_cerebellum_custom_annotation_sensitivity_R", "sensitivity",
          c(brain_primary, "GSE36315_cerebellum_custom_annotation"), "Grouped-brain sensitivity adding custom-annotated GSE36315 cerebellum.", "custom annotation")
add_model("brain_expression_gse36315_both", "post-mortem brain", "brain_expression_grouped_plus_GSE36315_two_region_collapsed_custom_annotation_sensitivity_R", "sensitivity",
          c(brain_primary, "GSE36315_within_study_collapsed"), "Grouped-brain sensitivity adding within-study-collapsed GSE36315.", "custom annotation")
add_model("brain_expression_gse36315_pfc", "post-mortem brain", "brain_expression_cortex_plus_GSE36315_prefrontal_custom_annotation_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE38322", "GSE102741", "GSE236761", "GSE59288", "GSE64018", "GSE36315_prefrontal_cortex_custom_annotation"), "Cortex sensitivity adding custom-annotated GSE36315 prefrontal cortex.", "custom annotation region")
add_model("brain_expression_gse36315_pfc", "post-mortem brain", "brain_expression_prefrontal_plus_GSE36315_custom_annotation_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE102741", "GSE59288", "GSE36315_prefrontal_cortex_custom_annotation"), "Prefrontal sensitivity adding custom-annotated GSE36315.", "custom annotation region")
add_model("brain_expression_gse36315_cere", "post-mortem brain", "brain_expression_cerebellum_plus_GSE36315_custom_annotation_sensitivity_R", "sensitivity",
          c("GSE38322", "GSE211154", "GSE269105", "GSE36315_cerebellum_custom_annotation"), "Cerebellum sensitivity adding custom-annotated GSE36315.", "custom annotation region")
add_model("brain_expression_gse36315_both", "post-mortem brain", "brain_expression_microarray_plus_GSE36315_custom_annotation_sensitivity_R", "sensitivity",
          c("GSE113834", "GSE28475-GPL6883", "GSE28521", "GSE38322", "GSE36315_within_study_collapsed"), "Microarray sensitivity adding custom-annotated GSE36315.", "custom annotation platform")

add_model("lcl_expression", "LCL", "lcl_expression_core_public_primary_R", "primary",
          c("GSE15402", "GSE15451", "GSE37772", "GSE4187"), "Public LCL ASD-control expression model.", "primary")
add_model("lcl_expression", "LCL", "lcl_expression_expanded_public_sensitivity_R", "sensitivity",
          c("GSE15402", "GSE15451", "GSE29918", "GSE37772", "GSE4187", "GSE7329"), "Expanded LCL sensitivity.", "expanded")
add_model("lcl_expression", "LCL", "lcl_expression_no_pooled_syndromic_sensitivity_R", "sensitivity",
          c("GSE15402", "GSE15451", "GSE29918", "GSE37772", "GSE4187"), "Expanded LCL sensitivity excluding pooled syndromic route.", "expanded")

write_model_outputs(model_specs, effects_by_input, output_dir, "expression")
message("Expression meta-analysis models completed.")

